// QUARTERMASTER SCRIPT BY LOTTO

[arsenal_box, player] call ace_arsenal_fnc_openBox;

_personalGreeting = 0;
_rNum = 0;

if ( uniform player == "u_lot_dress_uniform_rpg" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Fucking hell you are late again, RPG.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "rpglate"; sleep 2; armoryGuy setRandomLip false;}; 
if ( uniform player == "u_lot_dress_uniform_biggie" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >What kind of name is Biggie Cheese? How did a muppet like you pass selection?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "biggie"; sleep 3; armoryGuy setRandomLip false;}; 
if ( uniform player == "u_lot_dress_uniform_xristos" && goggles player == "G_Squares_Tinted" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Now that's a fine piece of fashion you are wearing, Private Xristos.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "xristos"; sleep 3; armoryGuy setRandomLip false;}; 
if ( uniform player == "u_lot_dress_uniform_chris" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Chris, stay away from the medical supplies. We don't want another accident.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "chris"; sleep 3; armoryGuy setRandomLip false;}; 
if ( uniform player == "u_lot_dress_uniform_base" ) then { titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I'm guessing you're the newcomer then?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "newcomer"; sleep 2; armoryGuy setRandomLip false; sleep 3;};   
if ( uniform player == "u_lot_dress_uniform_martin" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Martin, go play Fortnite.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "martin"; sleep 3; armoryGuy setRandomLip false;}; 
if ( uniform player == "u_lot_dress_uniform_lotto" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Lotto, here you are eating again. Fucking hell.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "lotto"; sleep 3; armoryGuy setRandomLip false;}; 
if ( uniform player == "u_lot_dress_uniform_eskimo" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >What kind of name is Eskimo? How did a muppet like you pass selection?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "eskimo"; sleep 3; armoryGuy setRandomLip false;};
if ( uniform player == "u_lot_dress_uniform_nightmare" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Nightmare, your music choice is terrible, shameful is what it is.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "nightmare"; sleep 3; armoryGuy setRandomLip false;};
if ( uniform player == "u_lot_dress_uniform_chubby" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Chubby, I can't believe how much fucking medical equipment you need!</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "chubby"; sleep 3; armoryGuy setRandomLip false;};
if ( uniform player == "u_lot_dress_uniform_ranger" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Sergeant Ranger, I have ordered more cigars for you.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "ranger"; sleep 3; armoryGuy setRandomLip false;};
if ( uniform player == "u_lot_dress_uniform_jewich" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >What kind of name is Jewich? How did a muppet like you pass selection?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "jewich"; sleep 3; armoryGuy setRandomLip false;};
if ( uniform player == "u_lot_dress_uniform_brown" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Hey Brown, chill out with the javelins. They cost a small fortune!</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "brown"; sleep 3; armoryGuy setRandomLip false;};

if ( uniform player == "u_m21_uniform_t09" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >It's been a brutal winter. I can't remember the last time it was this cold, and for this long.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "winter"; sleep 3; armoryGuy setRandomLip false;};
if ( uniform player == "u_m21_uniform_closed_t09" ) then { _personalGreeting = 1; titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >It's been a brutal winter. I can't remember the last time it was this cold, and for this long.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "winter"; sleep 3; armoryGuy setRandomLip false;};


if (_personalGreeting == 0 ) then { _rNum = selectRandom [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]; };

if ( _rNum == 1 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >What do you need?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "whatdoyouneed"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 2 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Stay sharp.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "staysharp"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 3 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Don't die out there.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "dontdieoutthere"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 4 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I ain't much for talkin'.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "aintmuchfortalking"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 5 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Need something?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "needsomething"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 6 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Hmm.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "hmm"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 7 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Everything alright?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "everythingalright"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 8 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I'm glad you're on our side.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "onourside"; sleep 2; armoryGuy setRandomLip false;};

if ( _rNum == 9 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Don't screw this up.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "dontscrewthisup"; sleep 1; armoryGuy setRandomLip false;};

if ( _rNum == 10 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Ugh. Your breath is foul. What've you been eating?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "whathaveyoubeeneating"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 11 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I'd hate to think what would happen if this fell into enemy hands.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "enemyhands"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 12 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I doubt any of us are coming back from this mission.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "comingback"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 13 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >No disrespect toward the General, but sometimes I wonder if he has got your best interest at heart.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "disrespectgeneral"; sleep 5; armoryGuy setRandomLip false;};

if ( _rNum == 14 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Keep an eye out for trouble. It's only a matter of time.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "keepeyeout"; sleep 2; armoryGuy setRandomLip false;};

if ( _rNum == 15 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I catch you stealing anything, I'll break your neck.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "catchyoustealing"; sleep 3; armoryGuy setRandomLip false;};

if ( _rNum == 16 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >We'll show those faithless dogs who this land belongs to.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "faithlessdogs"; sleep 3; armoryGuy setRandomLip false;};

if ( _rNum == 17 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >The gods gave you two hands, and you use them both for your weapon. I can respect that.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "godsgaveyoutwohands"; sleep 5; armoryGuy setRandomLip false;};

if ( _rNum == 18 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Now that's a smart weapon. Light, strong, useful. Crack some skulls for me.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "smartweapon"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 19 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I used to be a soldier like you, but then I took a bullet to the knee.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "bulletknee"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 20 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Sometimes you just do what needs to be done. You don't have to hate a man to kill him.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "hateman"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 21 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Take care of your armor, and it'll take care of you.</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "armor"; sleep 2; armoryGuy setRandomLip false;};

if ( _rNum == 22 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >I trust you're not planning any trouble. What can I do for you, friend?</t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "trouble"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 23 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Lot of history in these walls. We're trying to make some more. It's a lucky time to be alive. </t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "historywalls"; sleep 4; armoryGuy setRandomLip false;};

if ( _rNum == 24 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Good to have you by my side, friend. I need reliable people around. </t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "reliablepeople"; sleep 3; armoryGuy setRandomLip false;};

if ( _rNum == 25 ) then {titleText ["<t align = 'center' valign = 'bottom' shadow = '2' color='#00ff00' size='1.2' font='PuristaSemibold' >Quartermaster Billy: </t><t color='#ffffff' size='1.2' font='PuristaMedium' >Got my hands full as usual. </t>", "PLAIN DOWN", -1, true, true]; armoryGuy setRandomLip true; armoryGuy say "handsfull"; sleep 2; armoryGuy setRandomLip false;};

